#!/bin/sh

docker run -itd \
  --name coturn \
  -p 3478:3478 \
  -p 3478:3478/udp \
  -p 5349:5349 \
  -p 5349:5349/udp \
  -p 49152-65535:49152-65535/udp \
  -v /root/coturn/turnconfig:/etc/turnconfig \
  -v /root/coturn/turnlog:/etc/turnlog \
coturn
