#!/bin/sh

#   -p 3478:3478 \
#   -p 3478:3478/udp \
#   -p 5349:5349 \
#   -p 5349:5349/udp \
#   -p 49152-65535:49152-65535/udp \

docker run -itd \
  --name coturn \
  -v /root/git/coturn-docker/turnconfig:/etc/turnconfig \
  -v /root/git/coturn-docker/turnlog:/etc/turnlog \
coturn
